CREATE TABLE IF NOT EXISTS food(
    fid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    mid INTEGER DEFAULT NULL REFERENCES mood(mid) ON DELETE SET DEFAULT,
    consumption_time INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL,
    type TEXT NOT NULL,
    amount INTEGER NOT NULL
);